version: '3'

services:
  caddy:
    image: caddy:2.4.3-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data:/data

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    expose:
      - 80
    environment:
      - PMA_ARBITRARY=${PMA_ARBITRARY}
      - PMA_ABSOLUTE_URI=${PMA_ABSOLUTE_URI}
